[main]
font=CaskaydiaCove Nerd Font:size=12
pad=12x12

[cursor]
style=beam

[colors-dark]
alpha=0.85
background=1a1a1a
foreground=eeeeee

## Selection colors
selection-foreground=1a1a1a
selection-background=ffffff

## Normal colors
regular0=1a1a1a  # black
regular1=f38ba8  # red
regular2=478061  # green
regular3=f9e2af  # yellow
regular4=478061  # blue
regular5=cba6f7  # magenta
regular6=94e2d5  # cyan
regular7=eeeeee  # white

## Bright colors
bright0=444444   # bright black
bright1=f38ba8   # bright red
bright2=478061   # bright green
bright3=f9e2af   # bright yellow
bright4=478061   # bright blue
bright5=cba6f7   # bright magenta
bright6=ffffff   # bright cyan
bright7=ffffff   # bright white
